// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzzbnqrfiqrllxzxvykv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6emJucXJmaXFybGx4enh2eWt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4NTYxNDQsImV4cCI6MjA3NjQzMjE0NH0.nh4_nn2fG8QWN-gFxl_U6aEmQ6nIpZnDJOFXd_a86tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});